name: Build and Deploy Next.js to Nginx

on:
  push:
    branches:
      - dev # Change this to your branch name if needed
  # pull_request:
  #   branches:
  #     - dev  # Trigger when a PR is merged into the dev branch
  workflow_dispatch:  # Manual trigger for the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for accessing EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Set up known hosts to avoid SSH prompts
      - name: Set up known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 5: Build the Next.js app
      - name: Build Next.js app
        run: |
          npm run build

      # Step 6: Deploy files to the Nginx server
      - name: Copy files to Nginx server
        run: |
          scp -r -i ~/.ssh/id_rsa ./out/ ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/usr/share/nginx/html/

      # Step 7: Reload Nginx to apply changes
      - name: Reload Nginx
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'sudo systemctl reload nginx'
